export const ROUTES = {
  login: '/login',
  resetPassword: '/reset-password',
  unauthorized: '/unauthorized',
  staffHome: '/staff',
  staffSchedule: '/staff/schedule',
  staffHistory: '/staff/history',
  staffProfile: '/staff/profile',
  managerDashboard: '/manager',
  managerAttendance: '/manager/attendance',
  managerSchedules: '/manager/schedules',
  managerEmployees: '/manager/employees',
  managerBranches: '/manager/branches',
  managerReports: '/manager/reports',
  managerAudit: '/manager/audit',
  managerSettings: '/manager/settings',
}
