export const ROUTES = {
  login: '/login',
  resetPassword: '/reset-password',
  unauthorized: '/unauthorized',
  staffHome: '/staff',
  staffHistory: '/staff/history',
  staffProfile: '/staff/profile',
  managerDashboard: '/manager',
  managerAttendance: '/manager/attendance',
  managerEmployees: '/manager/employees',
  managerBranches: '/manager/branches',
  managerReports: '/manager/reports',
  managerAudit: '/manager/audit',
  managerSettings: '/manager/settings',
}
